### ISSUE TITLE
As potential user, I want to see a demo of the application

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/archiefvernietigingscomponent#125]
AVC=Archiefvernietingscomponent

**Tasks**

**0. Prepare a demo instance of Open Zaak with a scheduled task to load in demo zaken that need to be destroyed**

- [x] Make sure Open Zaak instance runs somewhere (@joeribekker )
- [x] Add demo-api credentials for AVC (@joeribekker )
- [x] Add demo-user credentials for AVC (@joeribekker )
- [x] In AVC: Create management command (ie. `manage.py create-demo-data`) to create demo data via the APIs (should already be configured or give an error). Create 2 zaaktypes, 1 documenttype for each zaak, 2 zaken per zaaktype, and each zaak has 1 document. (@SilviaAmAm )

**1. Create demo data that in AVC**

- [x] Create fixture with default roles (done in #121 ?) I think these can be loaded by naming them `initial_data.json` or so since they are essential (?) (@SilviaAmAm )
- [x] Create fixture with demo users ( `demo.json`) for each role (same username as password, username should start with `demo-`) (@SilviaAmAm )

**2. Add demo mode to the application**

- [x] Add setting `AVC_DEMO_MODE` (default `False`, can read from environment) (@SilviaAmAm )

**3. Add startpage to app**

- [x] Create startpage (@joeribekker )
- [x] If demo mode enabled, show a startpage on the base url. (if not enabled, redirect to login is fine as it is now) (@SilviaAmAm )
- [x] On startpage, show roles and login-credentials for them (filter on users `demo-` and show password=username) (@SilviaAmAm )

**4. Switch roles easily**

_See also screenshot below_

- [x] Create template tag to show demo users in a panel on the right side. Only works in demo mode. (@SilviaAmAm )
- [x] Make the users clickable which triggers a login action (only works in demo mode). (@SilviaAmAm )

**5. Tutorial**

_See also screenshot below_

- [ ] Extend the panel by showing a textual proces/tutorial to follow for the logged in user/role.

**6. Document demo setup**

- [x] Add documentation on how to set up the demo (load demo data, configure AVC to connect to OZ, configure OZ, enable demo mode)

![image](https://user-images.githubusercontent.com/96970/106156667-1cb1f700-6182-11eb-9775-08740a042419.png)
[snippet.txt](https://github.com/maykinmedia/record-management-app/files/5888170/snippet.txt)

**Comment by joeribekker** [comment]
Test Open Zaak instance: open-zaak.test.maykin.opengem.nl

**Comment by joeribekker** [comment]
Added startpage here: https://github.com/maykinmedia/archiefvernietigingscomponent/pull/128

**Comment by joeribekker** [comment]
Moving...

> 5. Tutorial
> See also screenshot below
> Extend the panel by showing a textual proces/tutorial to follow for the logged in user/role.

to its own ticket.
