### ISSUE TITLE
Als RM wil ik dat er automatisch een zaak wordt aangemaakt in Open zaak op het moment wanneer de VL definitief is en de vernietiging wordt uitgevoerd. De mogelijkheid om de lijst te downloaden in het Archiefvernietigingscomponent dient aanwezig te blijven.

### ISSUE THREAD

**Issue by renzoramaekers** [maykinmedia/archiefvernietigingscomponent#155]
**Tasks**

* [x] Optioneel maken om een Zaak aan te maken
* [x] Zaak-koppeling configureerbaar maken: Zaaktype, Statustype, Resultaattype, Documenttype
* [x] Zaak aanmaken van geconfigeerd zaaktype
* [x] Document (=Rapport van vernietiging) toevoegen met geconfigeerd documenttype
* [x] Resultaat van geconfigeerd resultaattype op zaak zetten
* [x] Zaak eindstatus zetten volgens geconfigureerd (zaak)statusttype
* [ ] Configureerbaar maken om wel/niet het rapport van vernietiging downloadbaar te bewaren in de applicatie. https://github.com/maykinmedia/archiefvernietigingscomponent/issues/261
* [x] Registreer zaaknummer aan vernietigingslijst

**Comment by joeribekker** [comment]
Specification on #86.

**Comment by SilviaAmAm** [comment]
https://github.com/maykinmedia/open-zaak/pull/2
