### ISSUE TITLE
Email notifications - Parent issue

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/archiefvernietigingscomponent#176]
Ticket https://github.com/maykinmedia/archiefvernietigingscomponent/issues/61

1. As a user, I want to receive email notification during the archiving process.
2. As a user, I want to configure if and how often I get the email notifications

Ticket https://github.com/maykinmedia/archiefvernietigingscomponent/issues/63

1. As an admin, I want to configure the text of the emails.

Split into 3 parts:

- [x] Part 1 (Issue https://github.com/maykinmedia/archiefvernietigingscomponent/issues/177)

- Since there are different types of emails, create some django choices `EmailTypes` with the choices `report, review_required, review_to_process`.
- Create a model for the automatic email. This could contain the fields: `type` (choice of `EmailTypes`, should be unique), `body`, `subject`. In this way, it will then be easy to customise the text of the different emails in the admin.
- Refactoring: for example creating a `notify` method to send emails.  
- Modify the method https://github.com/maykinmedia/archiefvernietigingscomponent/blob/master/src/archiefvernietigingscomponent/destruction/models.py#L98 to send an email once someone is assigned to a list.
- Modify the task https://github.com/maykinmedia/archiefvernietigingscomponent/blob/master/src/archiefvernietigingscomponent/destruction/tasks.py#L166 to make use of the configured email text/subject.

- [x] Part 2 (issue https://github.com/maykinmedia/archiefvernietigingscomponent/issues/178)

- Add a model to store user email-preferences `EmailPreferences`. Should have a FK to a user, and a choice of preferences, for example:
	- Email as soon as an action occurs
	- Never email

- [ ] Part 3 (issue https://github.com/maykinmedia/archiefvernietigingscomponent/issues/187)

- Add default email text through fixture
- Make it possible to use variables inside the default email texts.
