### ISSUE TITLE
Als recordmanager wil ik een zaak kunnen herwaarderen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/archiefvernietigingscomponent#240]
_Kans is dat dit een duplicate is_ Story ingebracht met kerngroep.

**Tasks**

* [x] Archiefactiedatum kunnen aanpassen -> OpenZaak
* [x] Archiefnominatie kunnen aanpassen -> OpenZaak
* [x] Archiefstatus -> OpenZaak
* [x] Reden toevoegen waarom dit aangepast wordt (dit is volgens mij een Header X-Toelichting die in de audit trail wordt opgenomen).
