### ISSUE TITLE
Send email reminder to the reviewer after a period of time

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/archiefvernietigingscomponent#247]
Part of #91 

**Tasks**

- [x] Add an optional field to the `DestructionListAssignee` to keep track of when a user was assigned to a list (for example `assigned_on`).
- [x] Populate the `assigned_on` field once the `DestructionList` is assigned to someone. (in the `assign` function of `DestructionList`, possibly in other places?)
- [x] Write a test to make sure that when you create a `DestructionList` through the view, one reviewer has the `assigned_on` field populated.
- [x] Write a test to check that when there is no one to assign to the list (i.e. the method `next_assignee` on the `DestructionList` returns `None`), the function `assign` does not break.
- [x] Add an `EmailTypeChoice` like `review_required_reminder` for this new type of automatic email.
- [x] Add a celery beat task that checks for non-completed DestructionLists that have an assignee and check for how long the user has been assigned for. If the user is NOT the author of the list, send a reminder email.
- [x] Write tests for the task
- [x] Add documentation
