### ISSUE TITLE
Als record manager wil ik kunnen zoeken naar afgesloten zaken waarvan de archiefactiedatum nog niet berekend kan worden

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#53]
zodat ik inzicht krijg in achterstallige administratie. 

[thema uit concept offerte: 1 Ophalen van zaken zonder berekende archiefactiedatum & bewerken archiefparameters]

**Tasks**

* [x] Knop toevoegen naast "Opstellen": "Toon zaken zonder archiefactiedatum"
* [x] Dit niewe scherm toont zaken met: Resultaat moet gezet zijn + Zaak afgesloten + Geen archiefactiedatum
* [x] Sorteer de lijst altijd archiefactiedatum (null is last) + zaaktype naam

Zie ook: #54 voor verder invulling van nieuwe scherm.

**Comment by SilviaAmAm** [comment]
For this issue, we need to be able to filter cases on:
- They are closed (`einddatum` is in the past or `einddatum` is null?)
- They have `archiefactiedatum` empty
- Their result is set (do all cases with `einddatum` have a result set?)

At the moment there is no way to filter for an empty `archiefactiedatum` or to filter at all for `einddatum` in OZ. So these should be added to the standard for this to have acceptable performance.

**Comment by SilviaAmAm** [comment]
It would also be ideal to be able to filter `zaaktype__in` and `bronorganisatie__in`
