### ISSUE TITLE
Als record manager wil ik -vanuit een overzicht van afgesloten zaken zonder archiefactiedatum- ontbrekende archiefgegevens kunnen aanvullen

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#54]
zodat de archiefactiedatum berekend kan worden. In voorkomende gevallen wil ik ook archiefgegevens aan kunnen passen 

[thema uit concept offerte: 1 Ophalen van zaken zonder berekende archiefactiedatum & bewerken archiefparameters]

**Tasks**

* [x] Knop toevoegen naast "Opstellen": "Toon zaken zonder archiefactiedatum"
* [x] Toon lijst van zaken zoals bij opstellen MAAR met de volgende wijzigingen:
* [x] + kolom: zaaknummer
* + zoekveld op zaaknummer => https://github.com/maykinmedia/archiefvernietigingscomponent/issues/254
* [x] + actie bij klikken: Instelen van archiefactiedatum IN OPEN ZAAK (en daarmee verdwijnt deze zaak dus uit deze lijst).

**Comment by joeribekker** [comment]
Gerelateerd aan #53
