### ISSUE TITLE
ik wil als proceseigenaar dat ik wijzigingsvoorstellen op de VL kan doen die goed aansluiten op wat een record manager kan aanpassen. 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#79]
Bij de terugkoppeling die de proceseigenaar doet is niet duidelijk wat de bedoeling is wat je precies wilt  de combinatie van knoppen om te wijzigen en uit te zonderen en mogelijkheden zijn wat verwarrend en sluiten niet aan op datgene wat een record manager te zien krijgt.  

Ik wil als proces eigenaar voor kunnen stellen dat de volgende twee archiefkenmerken gewijzigd kunnen worden: 1) de archieftactiedatum, en 2) de archiefnominatie (bewaren of vernietigen).  Dit zijn ook de kenmerken die de record manager nu kan aanpassen. Daarnaast wil ik voor kunnen stellen om een zaak van de VL te halen, zonder aanpassing van archiefkenmerken. 

Zie ter vergelijking hieronder het scherm waarin proceseigenaar een voorstel doet, en hoe zich dat vertaalt naar datgene wat een record manager ziet. 

Hiermee samen hangt: bij het verwerken van het commentaar van een proces eigenaar, wil ik als record manager 1) de archiefactiedatum kunnen wijzigen, 2) de archiefnominatie kunnen wijzigen. Daarnaast wil ik de zaak van de VL halen met behoud van archiefkenmerken.
Dit kan nu al, maar de combinatie van knoppen en archiefkenmerken is wat verwarrend (je kunt nu bijvoorbeeld archiefkenmerk vernietigen in combinatie met de knop Keep item kiezen. Dat is niet intuitief.

[overig - usability]

**Tasks**

* [x] Uitzonderen knop verwijderen (dit is eigenlijk een aanpassing met als comment "uitzonderen".
* [x] Hierdoor mag ook bij de recordmanager de "suggestion" verwijderd worden
* [x] Aanpassen -> Voorstel tot aanpassen
* [ ] ~Akkoord mag weg (verifieer even wat het gedrag nu is, doet het iets of niet?)~ => If a reviewer asks for changes but then changes their mind about a zaak, without the akkoord button there is no way of removing the comment on a zaak.

**Comment by JurjenBert** [comment]
![record manager](https://user-images.githubusercontent.com/40294293/99681322-4cf06180-2a7e-11eb-8e6c-45fa18f500c8.PNG)
![proceseigenaar](https://user-images.githubusercontent.com/40294293/99681326-4d88f800-2a7e-11eb-9141-6e3bdc3a4bd0.PNG)

**Comment by RitaBerghuis** [comment]
Het aanpassen van de archiefnominatie en de archiefactiedatum is onderdeel van de functionaliteit van het AVC. 
Is dit dan altijd de recordmanager die dit doet? Of moeten we ook rekening houden met de mogelijkheid dat een proceseigenaar of diens medewerker dat doet?

Ook het raadplegen van de zaak vanuit het AVC zou mogelijk moeten zijn. Dit zou bijvoorbeeld kunnen door middel van een deeplink naar een (generiek) zaakafhandelcomponent.
