### ISSUE TITLE
Als recordmanager wil ik inzicht hebben in vernietigingslijsten die te lang onderhanden blijven,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#91]
zodat ik in voorkomende gevallen actie kan ondernemen. 

**Tasks**

* [x] Configuratie toevoegen voor aantal dagen dat een VL open mag staan
* [x] Na bovenstaande dagen, notificatie (mailtje) sturen naar diegene die nog geen actie (er is nog geen feedback terug naar de RM) heeft ondernomen (als iemand te lang "assigned" is). https://github.com/maykinmedia/archiefvernietigingscomponent/issues/247
* [x] Visuele indicator (rood) op het lijst item zien dat een VL te lang open staat (dit ziet de RM) ook na die X dagen.
* [x] Mogelijkheid tot annuleren van (nog niet beoordeelde) vernietitingslijst (door RM).
* [x] Mailtemplate toevoegen.

@renzoramaekers levert een standaard tekstje aan.

**Comment by renzoramaekers** [comment]
Beste …..,

U heeft kortgeleden een notificatie ontvangen over de Vernietigingslijst die wacht op uw goedkeuring.
Wij zien dat u nog niet geregeerd heeft, wilt u zo spoedig mogelijk op de Vernietigingslijst reageren.
